### ISSUE TITLE
Resource defaults are not rendered

### ISSUE THREAD

**Issue by lchi** [aespinosa/cookbook-kube#11]
Hello!

I was trying to use this cookbook to get started with launching a Kubernetes cluster, but noticed that a basic declaration like:
```
kubelet_service 'kubelet' do
  action [:create, :start]
  address '127.0.01'
end
```
does not render the default properties for the `systemd` ExecStart option. As it stands I don't think any of the resources can render out default properties.

---
Actual behavior:
```
# in /etc/systemd/system/kubelet.service
ExecStart=/usr/sbin/kubelet
```
Expected behavior:
```
# in /etc/systemd/system/kubelet.service
ExecStart=/usr/sbin/kubelet --address=0.0.0.0 --allow-privileged=false ...
```

---
Is this intended? If not, I believe the [fix could be simple](https://github.com/aespinosa/cookbook-kube/blob/master/libraries/command_generator.rb#L32) and I'd be happy to implement it.

**Comment by aespinosa** [comment]
Hi,

When I used the resource defaults, I based it off the commandline defaults in http://kubernetes.io/docs/admin/kubelet/ (and on other binaries).  So it if it the default value in the resource, then not having the flag should have the same intended effect.

**Comment by lchi** [comment]
I see, thanks!
