### ISSUE TITLE
kubeadm init

### ISSUE THREAD

**Issue by kplimack** [aespinosa/cookbook-kube#22]
what setup is required in lieu of running `kubeadm init` to generate certificates, etc ?

**Comment by aespinosa** [comment]
you would probably have to follow something like kubernetes the hardway and apply those in automating it in chef if you want. I will welcome a more non-trivial reference implementation aside from the one I initially wrote as a test-kitchen test

**Comment by andres-de-castro** [comment]
Figured this out by providing etcd with a ca.pem + ca-key.pem in /etc/kubernetes/pki/etcd

Kubeadm required only the above certificate (not they key) in /etc/kubernetes/pki/etcd, it also needed an etcd client.pem and client-key.pem, a DIFFERENT ca.pem and ca.key in /etc/kubernetes/pki and we also generated the service account (sa.pub and sa.key) a priori.
