### ISSUE TITLE
Default instantiation throws errors about auth...

### ISSUE THREAD

**Issue by elijah** [aespinosa/cookbook-kube#24]
I tried instantiating a simple master with the example resource declarations from README.md - I get the following, along with a daemon startup failure:

```Jan 31 12:37:13 pavlov kube-apiserver[736]: I0131 12:37:13.678278     736 server.go:112] Version: v1.7.6
Jan 31 12:37:13 pavlov kube-apiserver[736]: W0131 12:37:13.680583     736 authentication.go:368] AnonymousAuth is not allowed with the AllowAll authorizer.  Resetting AnonymousAuth to false. You should use a different authorizer``

**Comment by elijah** [comment]
It is my belief that if we want to set the default authorization_mode to AlwaysAllow, the anonymous_auth property must default to false (instead of true) to prevent this message from being emitted and confusing systemd into thinking a failure has occurred.

**Comment by elijah** [comment]
My theory here seems to be supported by https://kubernetes.io/docs/admin/kubelet-authentication-authorization/ -- though this also suggests that the cookbook should be enhanced to add additional authentication methods (like x.509...).

**Comment by aespinosa** [comment]
I  follow whatever's the default settings upstream and `--anonymous-auth` defaults to `true`: https://kubernetes.io/docs/reference/generated/kube-apiserver/

I think it's an upstream problem with kubernetes if the `kube-apiserver` fails when running it without any args.
