### ISSUE TITLE
Kubelet 1.9 does not pickup kubeconfig in default location

### ISSUE THREAD

**Issue by mattlqx** [aespinosa/cookbook-kube#25]
When using `kubelet_service` with v1.9, the kubeconfig (and therefore the api server address) does not get picked up without the `--kubeconfig` argument. Explicitly setting this argument as the `/var/lib/kubelet/kubeconfig` doesn't help either as the command generator doesn't add flags that are the default. Currently, you have to specify a kubeconfig path that isn't the default in order to get kubelet to work properly.

**Comment by aespinosa** [comment]
yes that was the design decision.   Is there an open issue for that in upstream kubelet 1.9?

You can try forcing the default with `KubeletService.property['kubeconfig'].default = '/something/else'` with excessive monkey patching

**Comment by aespinosa** [comment]
If the `kubelet` doesn't enforce its own defaults. then i think it's a problem with upstream kubernetes itself.
