### ISSUE TITLE
RFC: apiserver/controller-manager/scheduler as pods

### ISSUE THREAD

**Issue by yugui** [aespinosa/cookbook-kube#5]
I usually apiserver, controller-manager, scheduler as containers with the official `hyperkube` image, and let `kubelet` manage those containers.

I am thinking of porting our recipes which manage such containerized daemons to this cookbook.
Do you accept such changes if I send a pull request?

It would be a set of new providers of the existing `kubernetes_*` resources.

**Comment by aespinosa** [comment]
Yes I agree that this is a common community use case. I can review the changes and figure out how we can get it merged together.

**Comment by aespinosa** [comment]
Closing for now. Re-open if you have a pull request for review
